---
- name: Install MacOS Applications for Daily Driver Use
  hosts: localhost

  roles:
    - role: system
      tags:
        - system
        - preflight
        - directories
        - dotfiles

    - role: macos
      tags:
        - macos
        - dock
        - finder
        - keyboard

    - role: apps
      tags:
        - apps
        - ui-apps
        - cli-apps
        - documentation-tools
        - networking

    - role: aws
      tags:
        - aws

    - role: azure
      tags:
        - azure

    - role: gcp
      tags:
        - gcp

    - role: dev-tools
      tags:
        - dev-tools
        - git-tools
        - gh-cli
        - golang
        - golang-tools
        - cicd
        - kubernetes

    - role: virtualization
      tags:
        - virtualization

    - role: editors
      tags:
        - editors

    - role: terminal
      tags:
        - terminal
        - ghostty
        - zsh
        - fonts
        - nvim

    - role: custom-tools
      tags:
        - custom-tools
        - demo
