---
- import_tasks: preflight.yml
  tags:
    - always
    - preflight

- import_tasks: directories.yml
  tags:
    - directories
    - install

- import_tasks: dotfiles.yml
  tags:
    - dotfiles
    - install
