---
- name: Install AWS CLI and tools
  community.general.homebrew:
    name:
      - awscli
      - aws-iam-authenticator
      - eksctl
    state: present
  when: install_aws | bool
  tags:
    - install
    - aws

- name: Tap granted repository
  community.general.homebrew_tap:
    name: common-fate/granted
    state: present
  when: install_aws | bool
  tags:
    - install
    - aws

- name: Install granted (AWS role assumption)
  community.general.homebrew:
    name: common-fate/granted/granted
    state: present
  when: install_aws | bool
  tags:
    - install
    - aws
