- name: Install tools for demo
  community.general.homebrew:
    name:
      - imagemagick
      - gifsicle
    state: present
  tags:
    - demo
    - custom-tools

- name: Install user-cube tools
  community.general.homebrew:
    name: "{{ custom_user_cube_tools }}"
    state: present
  tags:
    - user-cube
    - custom-tools