- name: Install tools for demo
  community.general.homebrew:
    name:
      - imagemagick
      - gifsicle
    state: present
  tags:
    - demo
    - custom-tools

- name: Add tap repositories for custom tools
  community.general.homebrew_tap:
    name: "{{ custom_user_taps }}"
    state: present
  tags:
    - custom-tools
    - install

- name: Install custom tools
  community.general.homebrew:
    name: "{{ custom_user_tools }}"
    state: present
  tags:
    - custom-tools
    - install