- name: Tap skhd-zig repository
  community.general.homebrew_tap:
    name: jackielii/tap
    state: present
  tags:
    - install
    - cli-apps

- name: Install laptop configuration tools
  community.general.homebrew:
    name:
      - koekeishiya/formulae/yabai
      - jackielii/tap/skhd-zig
      - fzf
      - zoxide
    state: present
  notify:
    - Start Yabai
    - Start skhd-zig
  tags:
    - install
    - cli-apps

- name: Install text interaction tools
  community.general.homebrew:
    name:
      - bat
      - jq
      - yq
      - ripgrep
      - yamllint
    state: present
  tags:
    - install
    - cli-apps

- name: Install linters and formatters
  community.general.homebrew:
    name:
      - shellcheck
      - shfmt
      - pylint
      - black
      - prettier
      - stylua
    state: present
  tags:
    - install
    - cli-apps
    - linters

- name: Monitoring tools
  community.general.homebrew:
    name:
      - htop
      - btop
    state: present
  tags:
    - install
    - cli-apps

- name: Install homebrew packages
  community.general.homebrew:
    name:
      - tree
      - watch
      - direnv
      - go-task
      - asciinema
      - yazi
      - kubectx
    state: present
  tags:
    - install
    - cli-apps