- name: Install Oh My Zsh
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  tags:
    - install
    - zsh

- name: Download powerlevel10k theme
  ansible.builtin.git:
    repo: "{{ zsh_theme_repo }}"
    dest: "{{ zsh_theme_dest }}"
    depth: 1
  tags:
    - install
    - zsh

- name: Install zsh plugins
  community.general.homebrew:
    name:
      - zsh-syntax-highlighting
      - zsh-autosuggestions
    state: present
  tags:
    - install
    - zsh

- name: Install pyenv
  community.general.homebrew:
    name: pyenv
    state: present
  tags:
    - install
    - zsh
    - pyenv

- name: Install nvm
  ansible.builtin.shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
  args:
    creates: "{{ lookup('env', 'HOME') }}/.nvm/nvm.sh"
  tags:
    - install
    - zsh
    - nvm
