- name: Install terraform
  community.general.homebrew:
    name:
      - terraform-docs
      - tflint
      - tfsec
      - terraform-ls
      - tenv
      - ansible-lint
    state: present
  tags:
    - install
    - iac
    - terraform

- name: Install opentofu language server
  community.general.homebrew:
    name: tofu-ls
    state: present
  tags:
    - install
    - iac
    - opentofu
